In [1]:
from utils import *
from preprocess import *

In [2]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [9]:
df = fetch_train_data('../data/train_data_all_filled.json')
df['fit'].replace('', np.nan)
df.dropna(subset=['fit'], inplace=True)
df.drop(labels=[
    'age', 'height', 'weight', 'bust_size', 'price', 'review_summary',
    'review', 'user_name', 'rating'
],
        axis=1,
        inplace=True)
labels = [
    0 if fit.startswith('S') else 1 if fit.startswith('T') else 2
    for fit in df['fit'].to_list()
]
df['fit'] = labels
cols = df.columns.to_list()
cols.remove('fit')
X, y = df[cols], df['fit']
encoder = OneHotEncoder()
X = encoder.fit_transform(X)
y = y.to_numpy()

In [10]:
clf = LogisticRegression(max_iter=5000)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
random_split_aggr(clf, X_train, y_train, X_test, y_test)

(array([0, 1, 2]), array([ 9460, 16423, 11483]))
(array([0, 1, 2]), array([ 9460, 16423, 11483]))
(array([0, 1, 2]), array([ 9460, 16423, 11483]))


accuracy  precision    recall       f1  f1_weighted  #small  \
result  0.644241   0.537961  0.584881  0.55475     0.657142    3013   

        #true2size  #large  
result       10625    3916